### ISSUE TITLE
GB Build Tool install error on RPi 3

### ISSUE THREAD

**Issue by fahimmac** [gonium/gosdm630#1]
Hi Mathias,
Great work you have done here with SDM630 meter. 

I also got the Eastron SDM630-MODBUS +RS485 USB adapter (+,- port ). 
USB adapter: http://www.ebay.de/itm/like/201548792231?lpid=106&chn=ps&ul_noapp=true

I am trying too install your code in my Raspberry pi 3. But while trying to install the _'GB build tool'_ using 

**"make dep"** 
command or 
**"go get github.com/constabulary/gb/..."** command, 

i encounter the following error:

##############################################################
pi@logger ~ $ cd tmtr/gosdm630

pi@logger ~/tmtr/gosdm630 $ sudo -s
root@logger:/home/pi/tmtr/gosdm630# make dep

make: Warning: File 'Makefile' has modification time 534336 s in the future
Installing GB build tool
 github.com/constabulary/gb/internal/untar
/usr/lib/go/src/pkg/github.com/constabulary/gb/internal/untar/untar.go:37: function ends without a return statement
/usr/lib/go/src/pkg/github.com/constabulary/gb/internal/untar/untar.go:53: function ends without a return statement
 github.com/constabulary/gb/internal/depfile
/usr/lib/go/src/pkg/github.com/constabulary/gb/internal/depfile/depfile.go:43: undefined: bufio.NewScanner
 github.com/constabulary/gb/cmd/gb/internal/match
/usr/lib/go/src/pkg/github.com/constabulary/gb/cmd/gb/internal/match/match.go:76: function ends without a return statement
 github.com/constabulary/gb/internal/vendor
/usr/lib/go/src/pkg/github.com/constabulary/gb/internal/vendor/depset.go:92: undefined: build.ImportComment
Makefile:15: recipe for target 'dep' failed
make: *** [dep] Error 2
root@logger:/home/pi/tmtr/gosdm630# exit
#####################################################################

pi@logger ~/tmtr/gosdm630 $ sudo -s
root@logger:/home/pi/tmtr/gosdm630# go get github.com/constabulary/gb/...

 github.com/constabulary/gb/internal/untar
/usr/lib/go/src/pkg/github.com/constabulary/gb/internal/untar/untar.go:37: function ends without a return statement
/usr/lib/go/src/pkg/github.com/constabulary/gb/internal/untar/untar.go:53: function ends without a return statement
 github.com/constabulary/gb/internal/depfile
/usr/lib/go/src/pkg/github.com/constabulary/gb/internal/depfile/depfile.go:43: undefined: bufio.NewScanner
 github.com/constabulary/gb/cmd/gb/internal/match
/usr/lib/go/src/pkg/github.com/constabulary/gb/cmd/gb/internal/match/match.go:76: function ends without a return statement
 github.com/constabulary/gb/internal/vendor
/usr/lib/go/src/pkg/github.com/constabulary/gb/internal/vendor/depset.go:92: undefined: build.ImportComment

root@logger:/home/pi/tmtr/gosdm630# 

######################################################################

I would be really grateful if you can let me know what may be the problem.

Also for the Hardware side i have connected the RS-485 USB adapter's (+) side to pin 9(A) and (-) side to pin 10(B) of the sdm630-Modbus meter. 

And do you think USB adapter which i am using will work without the resistors ?

Thank you so much again for your help.

**Comment by gonium** [comment]
Hi fahimmac,

thanks for your report. As for the first part, ``make dep``: This is a build error with regard to the ``gb`` build tool. I looked at https://github.com/constabulary/gb/blob/master/internal/untar/untar.go - the code of @constabulary looks fine. I would assume that your local download got somehow corrupted. I'm sorry to not be able to pinpoint this, but I think this is an issue with your local copy of the ``gb`` tool.

That said I just uploaded binaries to the release 0.2.0. You should be able to download them from here:

https://github.com/gonium/gosdm630/releases/tag/v0.2.0

Please use ``sdm630_httpd-linux-arm`` for your Raspberry Pi. You need to set the executable flag, something like

    # chmod u+x sdm630_httpd-linux-arm

and then

   # ./sdm630_httpd-linux-arm -s /dev/ttyUSB0 -d 1 -v

for querying the modbus device 1 with your adapter at ``/dev/ttyUSB0``.

As for the USB adaptor with the resistors: It depends on your cabling. For short cables (<1m) I had success without any resistor at all. For longer cables I recommend at least the 120 ohm resistors at each end of the cable. 

Hope this helps, if not, please reopen the issue.

-Mathias
