### ISSUE TITLE
Connect few meters to one dongle

### ISSUE THREAD

**Issue by poratnir1** [gonium/gosdm630#114]
Is it possible to read two meters using same service ?
or using same converter?

or need to add two services?

**Comment by J-A-U** [comment]
As the name says Modbus is a communication-bus. On a bus may a bunch of clients be connected to one converter, each with a different address. You tell gosdm the devices on the bus with paramter -d. For example
`-d SDM:22,SDM:23`
two Eastron SDM-meters, one with adress 22, one with 23.

**Comment by andig** [comment]
You can connect multiple meters but they must have different modbus ids.

**Comment by andig** [comment]
I feel this has been answered. If not please reopen.

**Comment by Poratnir** [comment]
Thanks!! working great

what speed is recommended?

**Comment by andig** [comment]
The exact speed that your meter requires!

**Comment by J-A-U** [comment]
Well, you have to take care alle meters on one bus are on the same baud- and framerate.
I suggest al least 9600bd. The SDM120 are delivered with 2400bd, thats pretty slow.
