### ISSUE TITLE
Firehose: Change longpolling API to websockets

### ISSUE THREAD

**Issue by gonium** [gonium/gosdm630#13]
Websockets are more efficient (no renegotiation of an HTTP connection) and allow two-way communication. There are also C++ libraries that make writing other client implementations easy, e.g. [BEAST websocket example](http://vinniefalco.github.io/beast/beast/quick_start.html#beast.quick_start.websocket_client).

**Comment by andig** [comment]
... or implement MQTT which seems to be becoming the de facto standard?

**Comment by andig** [comment]
See https://github.com/gonium/gosdm630/pull/38 for an implementation
