### ISSUE TITLE
ModBus Adaptor error rate

### ISSUE THREAD

**Issue by art0** [gonium/gosdm630#130]
Do you sell any of your homebrewed Modbus USB adaptors. I am running a setup with cheap USB-ones with no ground and get 
"Modbus": {
  "Requests": 8822,
  "RequestsPerMinute": 1643.5757367508729,
  "Errors": 61,
  "ErrorsPerMinute": 11.364556783246798

Is this a normal number?

**Comment by J-A-U** [comment]
I never checked the stats, but i have much less problems since i changed from a cheap chinese adapter to Digitus DA-70157.

**Comment by andig** [comment]
I feel this has been answered?
