### ISSUE TITLE
High load on raspberry

### ISSUE THREAD

**Issue by andig** [gonium/gosdm630#20]
I have a raspberry pi3 with two SDM630 attached via USB connector on one bus running at 9600 baud. When the http daemon is running the load is `0.65` when a single browser window is connected load is `1.25`.

This seems rather high given that the pi3 is quite capable?

**Comment by miroslavpetrov** [comment]
I am currently testing on Raspberry Pi 1 Model B+ and cpu usage is 75% only by sdm630_httpd.

**Comment by dimagoltsman** [comment]
im with RPI3 and besides the high cpu, it uses 900 MB of memory and stops responding every few days. is there a way to just get single measurement without starting the server?

**Comment by MatzeJoerling** [comment]
RPI A, RS485 shield, nodered querying every 2 sec, no browser, => load 0.25

**Comment by ABCarnage** [comment]
Had to put baudrate to 2400 baud to get 4 seconds latency (tested by pulling out devices). 9600 baud gave me a whopping 20 seconds. (using RaPi Model B 1, so yeah. But it works.)

**Comment by andig** [comment]
Imho the problem is not the http daemon but the fact that the longpoll library constantly hits the httpd. I'm working on moving from longpoll to websockets which should improve the load.

**Comment by andig** [comment]
Closing as duplicate of #13

**Comment by andig** [comment]
See https://github.com/gonium/gosdm630/pull/38 for a websocket implementation- i would appreciate test feedback
