### ISSUE TITLE
RS485 Board

### ISSUE THREAD

**Issue by preussal** [gonium/gosdm630#30]
Hi,
do you think that this
[Raspberry Pi Shield - RS485-Schnittstelle](https://www.reichelt.de/Entwicklerboard-Zubehoer/RPI-RS485/3/index.html?ACTION=3&GROUPID=8244&ARTICLE=162304) for ~ 10€ 
or this
[RS422 / RS485 Shield für Raspberry Pi](https://www.hwhardsoft.de/deutsch/projekte/rs485-shield/) for ~ 30€ or this 
[RS485 Pi](https://www.abelectronics.co.uk/p/77/RS485-Pi) 

or this USB Stick
[USB-RS485-Bridge mit Gehäuse](https://shop.in-circuit.de/product_info.php?cPath=38&products_id=81) 25€

would work too.

Grüße aus München

**Comment by ABCarnage** [comment]
I use a USB-RS485 bridge with 3 ports (A,B,GND) from China which cost so much less than your options. But it should work. 
Hint: Raspberry Pi can't get the requests out fast enough when on 9600 baud (20 seconds latency). We chose for 2400 baud which gives about 4 seconds latency.

**Comment by andig** [comment]
I've been using InCircuit https://shop.in-circuit.de/product_info.php?products_id=81 for ages and its working stable with two Eastron meters.
