### ISSUE TITLE
reports zero values on startup

### ISSUE THREAD

**Issue by TheCount** [gonium/gosdm630#9]
When gosdm starts but has not read out all values from the modbus yet, the JSON entities corresponding to the unread values are zero. This can be confusing because zero might be a valid value. A better choice might be to leave out these entities, or give them a JSON value of null.

**Comment by gonium** [comment]
This is correct. I changed the behaviour:

````
{"UniqueId":"Instrument23","Timestamp":"2017-06-22T16:32:13.217469202+02:00","Unix":1498141933,"ModbusDeviceId":23,"Power":{"L1":0,"L2":0,"L3":0},"Voltage":{"L1":235.1999969482422,"L2":0,"L3":0},"Current":{"L1":0,"L2":0,"L3":0},"Cosphi":{"L1":1,"L2":0,"L3":null},"Import":{"L1":null,"L2":null,"L3":null},"TotalImport":null,"Export":{"L1":null,"L2":null,"L3":null},"TotalExport":null,"THD":{"VoltageNeutral":{"L1":null,"L2":null,"L3":null},"AvgVoltageNeutral":null}}
````

In this example, all values up to ``Cosphi.L2" are already read from the smart meter and therefore initialized. The other values are ``null``.
