### ISSUE TITLE
Binary =/= 0.7.0

### ISSUE THREAD

**Issue by J-A-U** [gonium/gosdm630#92]
The binary from https://github.com/gonium/gosdm630/releases/download/v0.7.0/sdm630-linux-arm.zip recognize himself as 0.6.0:
http://localhost:8080/#about

> This installation runs GoSDM630 version 0.6.0 (compiled with go1.11)

Issue #59 seems to be still a thing in this one:

> pi@bananapi:~$ mosquitto_sub -h localhost -v -t sdm630/#
sdm630/status disconnected
sdm630/status connected
sdm630/status disconnected
sdm630/status disconnected
sdm630/status disconnected
sdm630/status disconnected
sdm630/status disconnected
sdm630/status disconnected
sdm630/status disconnected
sdm630/status disconnected
sdm630/status disconnected
sdm630/status disconnected

**Comment by andig** [comment]
There will be an 0.8 release in short time. The disconnected is only visual, working as expected. I'll close this one in favor of spending time on 0.8.
